channels:
  - conda-forge
  - bioconda
  - chem_data
  - https://conda.rosettacommons.org
dependencies:
  - python=3.12
  - setuptools>=71.0.2,<80.9
  - biopython=1.88
  - cctbx-base=2025.9
  - chem_data::chem_data=2026.9
  - fpocket=4.2.2
  - freesasa=2.2.1
  - numpy=1.26.4
  - openstructure=2.11.1
  - openbabel
  - pandas=2.3.3
  - scipy=1.13.1
  - vina=1.2.6
  - prody       # for Normal Mode Analysis
  - jupyterlab  # For testing notebooks, remove if unused
  - https://conda.rosettacommons.org::rosetta=2025.12+release.05ba3ce142
