name: allopep
channels:
  - defaults
  - conda-forge
  - bioconda
  - nvidia
  - pyg
  - pytorch
  - salilab
  - https://conda.graylab.jhu.edu
dependencies:
  - python=3.12.11
  - biopython=1.85
  - fpocket
  - freesasa=2.2.1
  - gemmi=0.7.3
  - h5py=3.14.0
  - ipywidgets=8.1.7
  - jupyter=1.1.1
  - jupyterlab-git=0.51.2
  - jupyterlab=4.4.4
  - libboost=1.86.0
  - matplotlib=3.10.3
  - mkl=2023.0.0
  - mmseqs2
  - more-itertools=10.7.0
  - numpy=2.3.1
  - openmm=8.2.0
  - pandas=2.3.1
  - pdbfixer=1.11
  - pillow=11.3.0
  - plotly=6.2.0
  - pyg::pytorch-scatter=2.1.2
  - pytorch::pytorch-cuda=12.4
  - pytorch::pytorch=2.4.1
  - pytorch::torchaudio=2.4.1
  - pytorch::torchvision=0.19.1
  - pyyaml
  - rdkit=2025.03.4
  - rosetta
  - salilab::dssp
  - scikit-image=0.25.2
  - scikit-learn=1.7.0
  - scipy=1.16.0
  - sympy=1.14.0
  - tensorboard
  - tqdm=4.67.1
  - xmltodict
  - pip
  - pip:
    - matplotlib-venn
    - nbdime
    - py-packman
    - SPARQLWrapper
    - statsmodels
    - ray
